name: farmer_johns_botanicals
description: Flutter e-commerce app for Farmer John's Botanicals
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.0.0
  shared_preferences: ^2.2.2
  http: ^1.1.0
  url_launcher: ^6.2.2
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  webview_flutter: ^4.4.2
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  logger: ^2.0.2
  dart_jsonwebtoken: ^2.9.3
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/products.json
    - assets/data/categories.json
    - assets/data/about.json
    - assets/images/
    - assets/images/products/
    - assets/images/uploads/

  # Fonts commented out until font files are added
  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/Montserrat-Regular.ttf
  #       - asset: assets/fonts/Montserrat-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Montserrat-SemiBold.ttf
  #         weight: 600
  #   - family: OpenSans
  #     fonts:
  #       - asset: assets/fonts/OpenSans-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/OpenSans-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/OpenSans-SemiBold.ttf
  #         weight: 600


